default: &default
  include_development_schemas: false
  include_testing_schemas: false
  tenant_id: "meru"
  tenant_name: "Meru"
  serialize_rendering: false
  validate_graphql_query: true

development:
  <<: *default
  include_development_schemas: true
  include_testing_schemas: false
  tenant_id: "meru-dev"

test:
  <<: *default
  include_development_schemas: true
  include_testing_schemas: true
  tenant_id: "meru-tst"

staging:
  <<: *default
  include_development_schemas: false
  include_testing_schemas: false
  tenant_id: "meru-stg"
  validate_graphql_query: false

production:
  <<: *default
  include_development_schemas: false
  include_testing_schemas: false
  tenant_id: "meru-prd"
  validate_graphql_query: false
