name: Continuous Integration

on:
  push:
    branches:
      - main
  pull_request:

env:
  PATH: /usr/sbin:/usr/bin:/sbin:/bin:/usr/local/bin:/usr/local/sbin

jobs:
  rubocop:
    if: github.event.pull_request.draft == false

    runs-on: ubuntu-latest
    steps:
      - uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: libpq-dev libvips libvips-dev
          version: 1.0

      - name: "Checkout code"
        uses: actions/checkout@v1

      - name: "Install Ruby"
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          ruby-version: 3.4.7

      - name: "Run Rubocop"
        env:
          RAILS_ENV: development
          RUBYOPT: "-W:no-deprecated -W:no-experimental"
        run: |
          bin/rubocop

  rspec:
    if: github.event.pull_request.draft == false

    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15.5-alpine
        ports: ["5432:5432"]
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: rails_test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

      redis:
        image: redis
        ports: ["6379:6379"]
        options: --entrypoint redis-server

    steps:
      - uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: libpq-dev libvips libvips-dev
          version: 1.0

      - name: "Checkout code"
        uses: actions/checkout@v1

      - name: "Install Ruby"
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          ruby-version: 3.4.7

      - name: "Run API specs"
        env:
          DATABASE_URL: "postgres://postgres:postgres@localhost:5432/rails_test"
          RUBYOPT: "-W:no-deprecated -W:no-experimental"
          RAILS_ENV: test
          KEYCLOAKADMIN_SERVER_URL: foo
          KEYCLOAKADMIN_SERVER_DOMAIN: foo
          KEYCLOAKADMIN_CLIENT_REALM_NAME: foo
          KEYCLOAKADMIN_CLIENT_ID: foo
          KEYCLOAKADMIN_CLIENT_SECRET: foo
          RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}
        run: |
          bin/rspec --tag ~skip_ci
